export const LOAD_POP_SHOWS = 'LOAD_POP_SHOWS';
export const LOAD_TREND_SHOWS = 'LOAD_TREND_SHOWS';
export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE';
export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const LOAD_IMAGES = 'LOAD_IMAGES';
export const GET_GENRES = 'GET_GENRES';